#!/usr/bin/env bash
# Script that setup Nginx web server on web-01 server + redirect

# Install Nginx
apt update -y && apt upgrade -youtube
apt install nginx -y

# Fill index page with text
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Redirect to youtube video
sed -i '/listen \[::\]:80 default_server;/a\	rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
