#!/usr/bin/env bash
# Script that setup Nginx web server on web-01 server + redirection + 404 not found

apt update -y && apt upgrage -y
apt install nginx -y

# Index page content
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Redirect to Youtube Video
sed -i '/listen \[::\]:80 default_server;/a\	rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Page not found (404)
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/TGUlwu4 permanent;$/a\        error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
