#!/usr/bin/env bash
# This script prints numbers from 1 to 100
# whith special messages when number is multiple of 3, 5 and 3 and 5 at the same time

for i in {1..100}; do
	if [ $((i % 5)) == 0 ] && [ $((i % 3)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi;
done
