#!/usr/bin/env bash
# This scri displays The content of the current directory in a list format
# where only the part of the name after the first dash is displayed

for i in * ; do echo "$i" | cut -d '-' -f 2 ; done
